apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: github-image-container
          image: ghcr.io/qxecutioner/webapplication1:latest
          env:
            - name: SERVICE_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: SERVICE_PREFIX

          ports:
            - containerPort: 80
