apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4-deployment
  labels:
    app: app4
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
        - name: github-image-container
          image: ghcr.io/qxecutioner/webapplication4:latest
          envFrom:
            - configMapRef:
                name: app4-configmap
          ports:
            - containerPort: 80
