apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapi-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard