name: Build and Push Multi-Container Images

on:
  workflow_call:
    inputs:
      app:
        required: true
      actor:
        required: true
      owner:
        required: true
      secrets:
        githubtoken:
          required: true
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.actor }}
        password: ${{ inputs.secrets.githubtoken }}

    # Build the Docker image
    - name: Build Docker Image
      run: |
        APP_NAME_LOWERCASE=$(echo "${{ inputs.app }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${{ inputs.owner }}/$APP_NAME_LOWERCASE:latest -f ./src/${{ inputs.app }}/Dockerfile ./src

    # Push the Docker image
    - name: Push Docker Image
      run: |
        APP_NAME_LOWERCASE=$(echo "${{ inputs.app }}" | tr '[:upper:]' '[:lower:]')
        docker push ghcr.io/${{ github.repository_owner }}/$APP_NAME_LOWERCASE:latest
