name: Build and Push Multi-Container Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - WebApplication1
          - WebApplication4

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build the Docker image
    - name: Build Docker Image
      run: |
        APP_NAME_LOWERCASE=$(echo "${{ matrix.app }}" | tr '[:upper:]' '[:lower:]')
        docker build -t ghcr.io/${{ github.repository_owner }}/$APP_NAME_LOWERCASE:latest ./src/${{ matrix.app }}/

    # Push the Docker image
    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/$APP_NAME_LOWERCASE:latest
