name: Deploy to Environments

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        app:
          - WebApplication1
          - WebApplication4

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     environment: [dev, staging, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build
        secrets: inherit
        with:
          app: ${{ matrix.app }}
          actor: ${{ github.actor }}
          owner: $${{ github.repository_owner }}
        
        

      # - name: Deploy to ${{ matrix.environment }}
      #   uses: ./.github/workflows/reusable-deploy.yml
      #   with:
      #     environment: ${{ matrix.environment }}
      #   secrets: inherit