name: Deploy to Environments

on:
  push:
    branches:
      - main

jobs:
  build:
    

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     environment: [dev, staging, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        strategy:
          matrix:
            app:
              - WebApplication1
              - WebApplication4
        uses: ./.github/workflows/build.yaml
        
        with:
          app: ${{ matrix.app }}
          actor: ${{ github.actor }}
          owner: ${{ github.repository_owner }}
        # secrets:
        #   githubtoken: ${{ secrets.GITHUB_TOKEN }}
          

        
        

      # - name: Deploy to ${{ matrix.environment }}
      #   uses: ./.github/workflows/reusable-deploy.yml
      #   with:
      #     environment: ${{ matrix.environment }}
      #   secrets: inherit