name: Deploy to Environments

on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  build:
    strategy:
      matrix:
        app:
          - WebApplication1
          - WebApplication4
    uses: ./.github/workflows/build.yaml
    secrets: inherit
    with:
      app: ${{ matrix.app }}
      actor: ${{ github.actor }}
      owner: ${{ github.repository_owner }}
          