name: Deploy to Environments

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     environment: [dev, staging, production]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/workflows/build
        # with:
        #   actor: ${{ github.actor }}
        #   secrets: ${{ secrets.GITHUB_TOKEN }}
        

      # - name: Deploy to ${{ matrix.environment }}
      #   uses: ./.github/workflows/reusable-deploy.yml
      #   with:
      #     environment: ${{ matrix.environment }}
      #   secrets: inherit